#' GRAFit: Pixel-by-pixel Surface Brightness Profile Plot.
#'
#' @description This high-level function calculates/plots the pixel-by-pixel surface brightness (SB).
#' @param image Image matrix; required, the galaxy image we want to fit a model to. The galaxy should be approximately central within this image.
#' @param main_source A list containing the specification of the main source in the cutout. This should be generated by the \code{ProFound}.
#' @param model The matrix of the model.
#' @param segim Segmentation matrix; optional, the full segmentation map of the image. If region is not provided then value of the central pixel is used to select the segmented pixels of the galaxy we want to fit. The log-likelihood is then computed using only these pixels. This matrix *must* be the same dimensions as image.
#' @param comp The components to be plotted; \code{bd}: bulge+disk, \code{b}: bulge only, \code{bd}: disk only.
#' @param centerPos The position of the center; i.e., c(x,y)
#' @param pix_scale Pixel scale in units of arcsecond/pixel.
#' @param zeropoint Numeric scalar; the magnitude zero point.
#' @param plot Logical; should the plot be generated? Otherwise only the values (SBs) will be returned.
#' @param modelPlot Logical; should the model profile be plotted?
#' @param title String; plot's title.
#' @param col A vector of colours.
#' @param legend Should a legend be annotated to the plot?
#' @param legend_lab A vector of legends.
#' @param legend_col A vector of legend's colours.
#' @return The pixel-by-pixel SB plot.
#' @author Hosein Hashemizadeh
#' @seealso \code{\link[GRAFit]{GRAFitEllipsePlot}}
#' @examples -
#' @export

GRAFitSBprofile <- function(image = image,
                            main_source = main_src,
                            model = NULL,
                            segim = segim,
                            comp = c("bd","b","d"),
                            centerPos = c(optim_xcen1,optim_ycen1),
                            pixel_scale = 0.03,
                            zeropoint = NULL,
                            plot = TRUE,
                            modelPlot = TRUE,
                            title = NULL,
                            col = NULL,
                            legend = TRUE,
                            legend_lab = c("Data", "Model+Noise", "Bulge", "Disk"),
                            legend_col = c('grey', 'green', 'red', 'blue')) {

  src_pix=image
  src_pix[segim != main_source$segID]=0
  r <- vector()
  mu <- vector()
  rDir <- vector()
  p = 0

  for(i in 1:nrow(src_pix)) {
    for(j in 1:nrow(src_pix)){
      if (src_pix[i,j] > 0) {
        p=p+1
        r[p]=sqrt((centerPos[1]-i)**2 + (centerPos[2]-j)**2)*pixel_scale
        mu[p]=zeropoint-2.5*log10(src_pix[i,j]/(pixel_scale**2))
      }
    }
  }

  if (modelPlot) {
    src_pix=model
    segim=segim
    src_pix[segim != main_source$segID]=0
    r_m <- vector()
    mu_m <- vector()
    rDir_m <- vector()
    p=0
    for(i in 1:nrow(src_pix)) {
      for(j in 1:nrow(src_pix)){
        if (src_pix[i,j] > 0) {
          p=p+1
          r_m[p]=sqrt((centerPos[1]-i)**2 + (centerPos[2]-j)**2)*pixel_scale
          mu_m[p]=zeropoint-2.5*log10(src_pix[i,j]/(pixel_scale**2))
        }
      }
    }

    if(plot) {
      if(comp=="bd") {
        magplot(r, mu, xlim = c(min(r),max(r)), ylim = c(27,min(mu)),
                pch=19, cex=0.3, xlab = "Projected Distance to Center /asec" ,
                ylab = expression(mu(mag/asec^2)), cex.lab=1.5, labels =1,
                grid = TRUE,main=title,col='grey')
      }

      par(new=TRUE)
      magplot(r_m, mu_m, xlim = c(min(r),max(r)), ylim = c(27,min(mu)),
              pch=19, cex=0.3, col=col, xlab = "", ylab = "", labels =F)
      if (legend) {
        if (comp=="bd") {
          legend("topright", c(legend_lab[1],legend_lab[2],legend_lab[3],legend_lab[4]),
                 col = c(legend_col[1],legend_col[2],legend_col[3],legend_col[4]),
                 pch = 19, y.intersp = 1, bg = 'white')
        } else if (comp=="b" | comp=="d") {
          legend("topright", c(legend_lab[1],legend_lab[2]),col = c(legend_col[1],legend_col[2]),
                 pch = 19, y.intersp = 1, bg = 'white')
        }

      }
    }

  } else {
    if(plot) {
      par(mar = rep(5, 4))
      magplot(r, mu, ylim = c(max(mu),min(mu)), pch=19, cex=0.3, xlab = "Projected Distance to the Center/asec" ,
              ylab = expression(mu(mag/asec^2)), cex.lab=1.5 ,side = c(1,2,3,4),main=title)
      legend("topright", c("Data"), pch = 19, bg = 'white')
    }
  }

}

# END
